spring:
  port: 8080
  servlet:
    context-path: /spring-e-shop
  datasource:
    url: jdbc:mysql://localhost:3306/spring_e_shop?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: "root"
    password: "!Q@W3e4r"
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

vaadin:
  url-mapping: /spring-e-shop
  pnpm-enabled: false
